<a href="https://colab.research.google.com/github/rishumishraprojects/Inverntory_Management/blob/main/HotelData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('AB_NYC_2019.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

In [4]:
cities = ['New-York','Los-Angeles','Chicago','Houston','Pheonix','Chicago','New-York']
rankings = [1,2,3,4,5,6,7]
scores = [9,10,9.2,6,7,1,8]

data = {'City':cities,'Ranking':rankings,'Score':scores}
df= pd.DataFrame(data)
print(df)

          City  Ranking  Score
0     New-York        1    9.0
1  Los-Angeles        2   10.0
2      Chicago        3    9.2
3      Houston        4    6.0
4      Pheonix        5    7.0
5      Chicago        6    1.0
6     New-York        7    8.0

In [11]:
df.duplicated('City').sum()

np.int64(2)

In [15]:
df.drop_duplicates(subset=['City'],keep = False)

          City  Ranking  Score
0     New-York        1    9.0
1  Los-Angeles        2   10.0
2      Chicago        3    9.2
3      Houston        4    6.0
4      Pheonix        5    7.0